source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.3'
use_frameworks!

target 'LodeStarApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LodeStarApp
  pod 'Alamofire', '~> 4.5'
  pod 'GVRKit'
end
